# Generated by Django 3.0.5 on 2020-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='secretary',
            field=models.BooleanField(default=False),
        ),
    ]
